In [1]:
import pandas as pd
import yfinance as yf
import numpy as np

In [11]:
import yfinance as yf
dat_ = yf.Ticker("MSFT")
# Get historical data into a DataFrame
df = dat_.history(period="max")  # Gets 1 month of data by default
print(df.head())  # Display first few rows


# Get splits and dividends data
splits_df = dat_.splits
dividends_df = dat_.dividends
analyst_price_targets_df = dat_.analyst_price_targets


# Print the results
print("Stock Splits:")
print(splits_df.tail())
print("\nDividends:")
print(dividends_df.tail())

print(analyst_price_targets_df)

                               Open      High       Low     Close      Volume  \
Date
1986-03-13 00:00:00-05:00  0.054485  0.062498  0.054485  0.059827  1031788800
1986-03-14 00:00:00-05:00  0.059827  0.063032  0.059827  0.061963   308160000
1986-03-17 00:00:00-05:00  0.061963  0.063566  0.061963  0.063032   133171200
1986-03-18 00:00:00-05:00  0.063032  0.063566  0.060895  0.061429    67766400
1986-03-19 00:00:00-05:00  0.061429  0.061963  0.059827  0.060361    47894400

                           Dividends  Stock Splits
Date
1986-03-13 00:00:00-05:00        0.0           0.0
1986-03-14 00:00:00-05:00        0.0           0.0
1986-03-17 00:00:00-05:00        0.0           0.0
1986-03-18 00:00:00-05:00        0.0           0.0
1986-03-19 00:00:00-05:00        0.0           0.0
Stock Splits:
Date
1994-05-23 00:00:00-04:00    2.0
1996-12-09 00:00:00-05:00    2.0
1998-02-23 00:00:00-05:00    2.0
1999-03-29 00:00:00-05:00    2.0
2003-02-18 00:00:00-05:00    2.0
Name: Stock Splits, dtype: float64

Dividends:
Date
2023-11-15 00:00:00-05:00    0.75
2024-02-14 00:00:00-05:00    0.75
2024-05-15 00:00:00-04:00    0.75
2024-08-15 00:00:00-04:00    0.75
2024-11-21 00:00:00-05:00    0.83
Name: Dividends, dtype: float64
{'current': 424.58, 'low': 420.0, 'high': 650.0, 'mean': 508.4636, 'median': 500.0}

In [7]:
#print head of dataframe 
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-12-17 00:00:00-05:00,451.010010,455.290009,449.570007,454.459991,22733500,0.0,0.0
2024-12-18 00:00:00-05:00,451.320007,452.649994,437.019989,437.390015,24444500,0.0,0.0
2024-12-19 00:00:00-05:00,441.619995,443.179993,436.320007,437.029999,22963700,0.0,0.0
2024-12-20 00:00:00-05:00,433.109985,443.739990,428.630005,436.600006,64263700,0.0,0.0
2024-12-23 00:00:00-05:00,436.739990,437.649994,432.829987,435.250000,19152500,0.0,0.0
2024-12-24 00:00:00-05:00,434.649994,439.600006,434.190002,439.329987,7164500,0.0,0.0
2024-12-26 00:00:00-05:00,439.079987,440.940002,436.630005,438.109985,8194200,0.0,0.0
2024-12-27 00:00:00-05:00,434.600006,435.220001,426.350006,430.529999,18117700,0.0,0.0
2024-12-30 00:00:00-05:00,426.059998,427.549988,421.899994,424.829987,13158700,0.0,0.0
2024-12-31 00:00:00-05:00,426.100006,426.730011,420.660004,421.500000,13246500,0.0,0.0
2025-01-02 00:00:00-05:00,425.529999,426.070007,414.850006,418.579987,16896500,0.0,0.0
2025-01-03 00:00:00-05:00,421.079987,424.029999,419.540009,423.350006,16662900,0.0,0.0
2025-01-06 00:00:00-05:00,428.000000,434.320007,425.480011,427.850006,20573600,0.0,0.0
2025-01-07 00:00:00-05:00,429.000000,430.649994,420.799988,422.369995,18139100,0.0,0.0
2025-01-08 00:00:00-05:00,423.459991,426.970001,421.540009,424.559998,15054600,0.0,0.0
2025-01-10 00:00:00-05:00,424.630005,424.709991,415.019989,418.950012,20201100,0.0,0.0
2025-01-13 00:00:00-05:00,415.239990,418.500000,412.290009,417.190002,17604800,0.0,0.0
2025-01-14 00:00:00-05:00,417.809998,419.739990,410.720001,415.670013,16935900,0.0,0.0
2025-01-15 00:00:00-05:00,419.130005,428.149994,418.269989,426.309998,19637800,0.0,0.0
2025-01-16 00:00:00-05:00,428.700012,429.489990,424.390015,424.579987,15279900,0.0,0.0

In [ ]:
dat